apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: architects-forum-deployment
  labels:
    app: architects-forum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: architects-forum
  template:
    metadata:
      labels:
        app: architects-forum
    spec:
      containers:
      - name: architects-forum
        image: dfalkner/architects-forum
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: architects-forum
spec:
  type: LoadBalancer
  selector:
    app: architects-forum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

